Repository cisco-sbg-ui/magna-react, pull requests merged in 2023-10, with the labels that each got.

#541 Check current ref in resize observer callback
  framework/utils/hooks.js
Labels: 1.0.0-beta.57

#542 Default toast placement to upper right
  framework/components/AToast/AToast.js
  framework/components/AToaster/AToastPlate.js
  framework/components/AToaster/AToaster.scss
  framework/components/AToaster/useAToaster.js
Labels: 1.0.0-beta.57

#537 feat: counter multiselect
  framework/components/AMultiSelect/AMultiSelect.cy.js
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/AMultiSelect/AMultiSelect.mdx
  framework/components/AMultiSelect/AMultiSelect.scss
  framework/components/AMultiSelect/AMultiSelectCounter.js
Labels: enhancement, 1.0.0-beta.57

#539 refactor: tag updates
  framework/components/ATag/ATag.cy.js
  framework/components/ATag/ATag.js
  framework/components/ATag/ATag.mdx
  framework/components/ATag/ATag.scss
Labels: enhancement, 1.0.0-beta.57

#548 fix: scroll state
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/AMultiSelect/AMultiSelect.scss
Labels: bug, 1.0.0-beta.59

#558 Use RobotoMono font
  framework/components/AApp/base/fonts.scss
  framework/components/ANetworkValue/ANetworkValue.js
  framework/components/ANetworkValue/ANetworkValue.mdx
  framework/components/ANetworkValue/ANetworkValue.scss
Labels: 1.0.0-beta.58

#557 Add skipValidation prop to inputs
  framework/components/ACheckbox/ACheckbox.js
  framework/components/ACombobox/ACombobox.js
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/ATextInput/ATextInput.js
  framework/components/ATextarea/ATextarea.js
Labels: 1.0.0-beta.58

#559 feat(ACombobox): allow dropdown menu to be scrollable with "maxHeight" prop
  framework/components/ACombobox/ACombobox.js
  framework/components/ACombobox/ACombobox.mdx
Labels: enhancement
