Repository cisco-sbg-ui/magna-react, pull requests merged in 2023-07, with the labels that each got.

#455 feat: add border on scroll
  framework/components/ADataTable/ADataTable.scss
  framework/components/ASimpleTable/ASimpleTable.js
  framework/components/ASimpleTable/ASimpleTable.scss
Labels: enhancement, 1.0.0-beta.48

#454 feat: magnetic adjustments and updates to checkbox
  framework/components/ACheckbox/ACheckbox.js
  framework/components/ACheckbox/ACheckbox.mdx
  framework/components/ACheckbox/ACheckbox.scss
  framework/styles/theme/default.scss
  framework/styles/theme/dusk.scss
  framework/styles/utilities/palette.scss
Labels: breaking change, 1.0.0-beta.48

#462 chore: add users icons
  framework/components/AIcon/atomicMap.js
  framework/components/AIcon/magnaIcons.js
  svg/users.svg
Labels: 1.0.0-beta.48

#460 Add focus-visible to AButton; Add focus to AButtonGroup buttons
  framework/components/AButton/AButton.scss
  framework/components/AButtonGroup/AButtonGroup.scss
  framework/styles/theme/default.scss
  framework/styles/theme/dusk.scss
  framework/styles/utilities/palette.scss
Labels: 1.0.0-beta.48

#470 Date range/#393
  framework/components/ADatePicker/ADatePicker.js
  framework/components/ADatePicker/ADatePicker.mdx
  framework/components/ADatePicker/ADatePicker.scss
  framework/components/ADatePicker/ADateRangePicker.cy.js
  framework/components/ADatePicker/ADateRangePicker.js
  framework/components/ADatePicker/DateInputs.js
  framework/components/ADatePicker/helpers.js
  framework/components/ADatePicker/index.js
  framework/components/ADatePicker/useGetADateRange.js
  framework/components/AFieldBase/AFieldBase.js
  framework/components/AInputBase/AInputBase.js
  framework/components/ATextInput/ATextInput.js
  framework/index.js
  framework/styles/theme/default.scss
  framework/styles/theme/dusk.scss
  framework/styles/utilities/palette.scss
Labels: enhancement, new component, 1.0.0-beta.48
