Repository cisco-sbg-ui/magna-react, pull requests merged in 2023-09, with the labels that each got.

#507 feat: Add page layout components
  docs/MdxHeadings.js
  docs/Playground.js
  framework/components/ABreadcrumb/ABreadcrumb.scss
  framework/components/ANetworkValue/ANetworkValue.js
  framework/components/ANetworkValue/ANetworkValue.mdx
  framework/components/ANetworkValue/ANetworkValue.scss
  framework/components/ANetworkValue/index.js
  framework/components/APageLayout/APageContainer.js
  framework/components/APageLayout/APageContainer.scss
  framework/components/APageLayout/APageDescription.js
  framework/components/APageLayout/APageDescription.scss
  framework/components/APageLayout/APageHeader.js
  framework/components/APageLayout/APageHeader.scss
  framework/components/APageLayout/APageLabel.js
  framework/components/APageLayout/APageLabel.scss
  framework/components/APageLayout/APageLayout.mdx
  framework/components/APageLayout/APageTitle.js
  framework/components/APageLayout/APageTitle.scss
  framework/components/APageLayout/APageTitleContent.js
  framework/components/APageLayout/APageTitleContent.scss
  framework/components/APageLayout/APageTitleText.js
  framework/components/APageLayout/content/APageTitleContentLeft.js
  framework/components/APageLayout/content/APageTitleContentRight.js
  framework/components/APageLayout/index.js
  framework/components/ATabs/ATabs.scss
  framework/index.js
  pages/[[...route]]/index.js
Labels: 1.0.0-beta.52

#510 fix: remove minDate return
  framework/components/ADatePicker/ADatePicker.js
Labels: bug, 1.0.0-beta.53

#514 Fix imports in form to reference files directly
  framework/components/AForm/AForm.js
Labels: 1.0.0-beta.53

#517 fix: override conflicting theme
  framework/components/AButton/AButton.scss
Labels: bug, 1.0.0-beta.54

#522 feat: add bold text to matched letters
  framework/components/AAutocomplete/AAutocomplete.js
  framework/components/AMultiSelect/AMultiSelect.js
  framework/utils/helpers.js
Labels: enhancement, 1.0.0-beta.55

#524 fix: swap clear icon
  framework/components/AInlineInputBase/AInlineInputBase.js
  framework/components/AInputBase/AInputBase.js
Labels: enhancement, 1.0.0-beta.55

#526 525 - swap to use padding, adjust a bit of spacing
  framework/components/APageLayout/APageContainer.scss
  framework/components/APageLayout/APageDescription.scss
  framework/components/APageLayout/APageHeader.scss
  framework/components/APageLayout/APageLayout.mdx
  framework/components/APageLayout/APageTitle.scss
Labels: 1.0.0-beta.55

#530 Rework checkbox to be more magnetic; fix size
  framework/components/AApp/base/color-helpers.scss
  framework/components/ACheckbox/ACheckbox.js
  framework/components/ACheckbox/ACheckbox.scss
  framework/styles/theme/default.scss
Labels: bug, 1.0.0-beta.55

#532 515 - add dot icon, script proof circle icons
  framework/components/AIcon/AIcon.scss
  framework/components/AIcon/atomicMap.js
  framework/components/AIcon/magnaIcons.js
  scripts/iconMap/index.js
  svg/check-circle.svg
  svg/dot.svg
  svg/minus-circle.svg
  svg/unsyncd/check-circle.svg
  svg/unsyncd/minus-circle.svg
  svg/unsyncd/x-circle.svg
  svg/x-circle.svg
Labels: 1.0.0-beta.55

#536 Add export icon
  framework/components/AIcon/AIcon.js
  framework/components/AIcon/AIcon.scss
  framework/components/AIcon/atomicMap.js
  framework/components/AIcon/magnaIcons.js
  scripts/iconMap/index.js
  svg/export.svg
Labels: 1.0.0-beta.47
