Repository cisco-sbg-ui/magna-react, pull requests merged in 2023-06, with the labels that each got.

#412 fix: fallback to focusing root element when the provided reference is empty
  framework/hooks/useFocusTrap/useFocusTrap.js
Labels: 1.0.0-beta.43

#416 Align ACombobox empty state with design
  framework/components/ACombobox/ACombobox.js
  framework/components/ACombobox/ACombobox.scss
  framework/components/AEmptyState/AEmptyState.js
  framework/components/AEmptyState/AEmptyState.scss
Labels: 1.0.0-beta.44

#421 feat: sticky header on scroll
  framework/components/ADataTable/ADataTable.js
  framework/components/ADataTable/ADataTable.scss
Labels: enhancement, 1.0.0-beta.44

#426 fix: display clear icon in text input based on the actual input value
  framework/components/ATextInput/ATextInput.cy.js
  framework/components/ATextInput/ATextInput.js
Labels: 1.0.0-beta.44

#418 feat: submenus
  framework/components/AList/AList.scss
  framework/components/AList/AListItem.js
  framework/components/AMenu/AMenu.cy.js
  framework/components/AMenu/AMenu.js
  framework/components/AMenu/AMenu.mdx
  framework/components/AMenu/AMenu.scss
Labels: enhancement, 1.0.0-beta.45

#437 fix: ressurect table lines
  framework/components/ADataTable/ADataTable.scss
Labels: bug, 1.0.0-beta.45

#435 #433 align ASwitch with magnetic; add small variant
  framework/components/ASwitch/ASwitch.js
  framework/components/ASwitch/ASwitch.mdx
  framework/components/ASwitch/ASwitch.scss
Labels: 1.0.0-beta.45

#436 #431 - add custom class and style props to AProgressbar elements
  framework/components/AProgressbar/AProgressbar.js
Labels: 1.0.0-beta.45

#394 #371 - add onlyIfTrunctated to ATriggerTooltip
  framework/components/ATriggerTooltip/ATriggerTooltip.js
  framework/components/ATriggerTooltip/ATriggerTooltip.mdx
  framework/hooks/useToggle/useToggle.js
  framework/hooks/useToggle/useToggle.mdx
Labels: 1.0.0-beta.46

#439 fix: stabilize width on input fields
  framework/components/AInputBase/AInputBase.scss
Labels: breaking change, 1.0.0-beta.46

#438 fix: update z-index of various components (#766)
  framework/changelog.mdx
  framework/components/ADatePicker/ADatePicker.scss
  framework/components/ADialog/ADialog.scss
  framework/components/ADrawer/ADrawer.scss
  framework/components/AMenuBase/AMenuBase.scss
  framework/components/APageOverlay/APageOverlay.scss
  framework/components/APanel/APanel.mdx
  framework/components/ASidebar/ASidebar.scss
  framework/components/ASlider/ASlider.scss
  framework/components/ATimeline/ATimeline.scss
  framework/components/AToaster/AToaster.scss
  framework/components/ATooltip/ATooltip.scss
  package-lock.json
  package.json
  pages/[[...route]]/index.js
Labels: 1.0.0-beta.46

#434 Default to medium size variant where applicable
  framework/components/ABadge/ABadge.mdx
  framework/components/ABadge/ABadge.scss
  framework/components/AButton/AButton.js
  framework/components/AButton/AButton.scss
  framework/components/AButtonGroup/AButtonGroup.js
  framework/components/AInputBase/AInputBase.js
  framework/components/ASelect/ASelect.js
  framework/components/ASelect/ASelect.mdx
  framework/components/ATextInput/ATextInput.mdx
Labels: 1.0.0-beta.46

#419 feat: Add AMultiSelect component
  framework/components/AMenu/AMenu.js
  framework/components/AMultiSelect/AMultiSelect.cy.js
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/AMultiSelect/AMultiSelect.mdx
  framework/components/AMultiSelect/AMultiSelect.scss
  framework/components/AMultiSelect/AMultiSelect.spec.js
  framework/components/AMultiSelect/AMultiSelectTag.js
  framework/components/AMultiSelect/index.js
  framework/components/ATag/ATag.scss
  framework/index.js
Labels: new component, 1.0.0-beta.46

#451 Icon button size
  framework/components/ATriggerTooltip/ATriggerTooltip.js
  framework/styles/utilities/mixins.scss
Labels: 1.0.0-beta.48

#449 A tag/#440
  framework/components/AIcon/magnaIcons.js
  framework/components/ASelect/ASelect.js
  framework/components/ATag/ATag.js
  framework/components/ATag/ATag.mdx
  framework/components/ATag/ATag.scss
  framework/styles/theme/default.scss
  framework/styles/theme/dusk.scss
  svg/check-circle.svg
  svg/minus-circle.svg
  svg/x-circle.svg
Labels: enhancement, breaking change, 1.0.0-beta.48

#452 chore: add bell slash
  framework/components/AIcon/atomicMap.js
  framework/components/AIcon/magnaIcons.js
  svg/bell-slash.svg
Labels: 1.0.0-beta.48
