Repository cisco-sbg-ui/magna-react, pull requests merged in 2023-03, with the labels that each got.

#266 fix: prevent AMenu components from closing AModal
  framework/components/AMenuBase/AMenuBase.js
  framework/hooks/useOutsideClick.js
Labels: bug

#276 feat: export additional React hooks and document them
  docs/Playground.js
  docs/Sidebar.js
  framework/components/AAutoTheme/AAutoTheme.js
  framework/components/AInView/AInView.js
  framework/components/AModal/AModal.js
  framework/hooks/useEscapeKeydown/useEscapeKeydown.js
  framework/hooks/useEscapeKeydown/useEscapeKeydown.mdx
  framework/hooks/useFocusTrap/useFocusTrap.js
  framework/hooks/useFocusTrap/useFocustrap.mdx
  framework/hooks/useInView/useInView.js
  framework/hooks/useInView/useInView.mdx
  framework/hooks/useMediaQuery/useMediaQuery.js
  framework/hooks/useMediaQuery/useMediaQuery.mdx
  framework/hooks/useOutsideClick/useOutsideClick.js
  framework/hooks/useOutsideClick/useOutsideClick.mdx
  framework/hooks/usePopupQuickExit/usePopupQuickExit.js
  framework/hooks/usePopupQuickExit/usePopupQuickExit.mdx
  framework/index.js
  framework/utils/hooks.js
Labels: documentation, enhancement

#285 fix: cleanup body scroll when AModal unmounts
  framework/components/AModal/AModal.js
Labels: bug

#291 fix: return boolean from modal propagation helper
  framework/components/AModal/AModal.js
Labels: bug

#298 Close drawer/#292
  framework/components/ADataTable/ADataTable.mdx
  framework/components/ADrawer/ADrawer.js
  framework/components/ADrawer/ADrawer.mdx
  framework/components/ADrawer/ADrawer.scss
  framework/components/ADrawer/ADrawerContent.scss
Labels: enhancement

#321 test: add cypress component tests
  .github/workflows/ci.yml
  cypress.config.js
  cypress.json
  cypress/fixtures/example.json
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/component-index.html
  cypress/support/component.js
  cypress/support/e2e.js
  framework/components/AAccordion/AAccordion.cy.js
  framework/components/AAlert/AAlert.cy.js
  framework/components/ADrawer/ADrawer.cy.js
  framework/components/AFieldBase/AFieldBase.cy.js
  framework/components/AInputBase/AInputBase.cy.js
  framework/components/AMenu/AMenu.cy.js
  framework/components/AMenuBase/AMenuBase.cy.js
  framework/components/AModal/AModal.cy.js
  framework/components/APopover/APopover.cy.js
  framework/components/ASelect/ASelect.cy.js
  framework/components/ATextInput/ATextInput.cy.js
  framework/components/ATriggerTooltip/ATriggerTooltip.cy.js
  framework/hooks/useEscapeKeydown/useEscapeKeydown.cy.js
  framework/hooks/useEscapeKeydown/useEscapeKeydown.js
  framework/hooks/useFocusTrap/useFocusTrap.cy.js
  framework/hooks/useOutsideClick/useOutsideClick.cy.js
  package-lock.json
  package.json
  pages/[[...route]]/index.js
Labels: help wanted
