Repository cisco-sbg-ui/magna-react, pull requests merged in 2023-12, with the labels that each got.

#561 feat: initial commit and proposed cds token integration
  .github/workflows/ci.yml
  .gitignore
  .npmrc
  framework/components/AAccordion/AAccordion.scss
  framework/components/AAlert/AAlert.scss
  framework/components/AApp/base/typography.scss
  framework/components/AButtonCard/AButtonCard.scss
  framework/components/AButtonGroup/AButtonGroup.scss
  framework/components/ACombobox/ACombobox.scss
  framework/components/ADatePicker/ADatePicker.js
  framework/components/ADatePicker/ADatePicker.scss
  framework/components/ADivider/ADivider.js
  framework/components/ADivider/ADivider.mdx
  framework/components/ADivider/ADivider.scss
  framework/components/AIcon/AIcon.scss
  framework/components/AIcon/magnaIcons.js
  framework/components/AMenu/AMenu.scss
  framework/components/AMultiSelect/AMultiSelect.scss
  framework/components/APagination/APagination.scss
  framework/components/ASimpleTable/ASimpleTable.scss
  framework/components/ASkeleton/ASkeleton.scss
  framework/components/ASlider/ASlider.scss
  framework/components/AStepper/AStep.js
  framework/components/AStepper/AStepper.scss
  framework/components/ASwitch/ASwitch.scss
  framework/components/ATimeline/ATimeline.mdx
  framework/components/ATimeline/ATimeline.scss
  framework/components/ATimeline/ATimelineItem.js
  framework/components/AToast/AToast.scss
  framework/styles/magnetic-tokens/index.scss
  framework/styles/magnetic-tokens/theme-dark.scss
  framework/styles/magnetic-tokens/theme-light.scss
  framework/styles/theme/dark.scss
  framework/styles/theme/default.scss
  framework/styles/theme/dusk.scss
  framework/styles/theme/index.scss
  framework/styles/theme/light.scss
  framework/styles/theme/mixins.scss
  framework/styles/theme/theme-map.scss
  framework/styles/utilities/palette.scss
  framework/styles/utilities/variables.scss
  package-lock.json
  package.json
  svg/alerts/Info.svg
  svg/alerts/Negative.svg
  svg/alerts/Positive.svg
  svg/alerts/Warning.svg
Labels: enhancement, dependencies, 1.1.0-beta.0

#581 feature: ADataTable takes header properties and pass them to ADataTableHeader ("td") element
  framework/components/ADataTable/ADataTable.cy.js
  framework/components/ADataTable/ADataTable.js
  framework/components/ADataTable/ADataTable.mdx
  framework/components/ADataTable/ADataTableCell.js
  framework/components/ADataTable/ADataTableCellTemplate.js
  framework/components/ADataTable/ADataTableHeader.js
  framework/components/ADataTable/ADataTableHeaderTemplate.js
  framework/components/ADataTable/ADataTableRow.js
  framework/components/ADataTable/ADataTableRowTemplate.js
  framework/components/ADataTable/ADataTableWrapper.js
  framework/components/ADataTable/useKeyboardNavigation.js
Labels: 1.1.0-beta.1

#582 #578 - add onRowMouseEnter and onRowMouseLeave to ADataTable
  framework/components/ADataTable/ADataTable.js
  framework/components/ADataTable/ADataTableCellTemplate.js
  framework/components/ADataTable/ADataTableHeaderTemplate.js
  framework/components/ADataTable/ADataTableRowTemplate.js
Labels: 1.1.0-beta.1

#543 More tab/#490
  cypress/support/component.js
  framework/components/AList/AList.scss
  framework/components/AMenu/AMenu.scss
  framework/components/ATabs/ATab.cy.js
  framework/components/ATabs/ATab.js
  framework/components/ATabs/ATabGroup.js
  framework/components/ATabs/ATabHeading.js
  framework/components/ATabs/ATabs.mdx
  framework/components/ATabs/ATabs.scss
  framework/components/ATabs/OverflowMenuTab.js
  framework/components/ATabs/index.js
  framework/index.js
  framework/styles/theme/theme-map.scss
  package-lock.json
  package.json
Labels: enhancement, breaking change, 1.1.0-beta.2
