Repository cisco-sbg-ui/magna-react, pull requests merged in 2023-11, with the labels that each got.

#560 Bump workflow npm-publish to use v2
  .github/workflows/beta.yml
Labels: 1.0.0-beta.59

#564 Rework state tracking in useMenuSpacing hook
  framework/components/AMenu/AMenu.scss
  framework/components/AMenuBase/hooks.js
Labels: 1.0.0-beta.59

#566 chore: audit fixes
  package-lock.json
Labels: dependencies

#568 Add play-circle icon
  framework/components/AIcon/atomicMap.js
  framework/components/AIcon/magnaIcons.js
  scripts/iconMap/index.js
  svg/play-circle.svg
Labels: 1.0.0-beta.59

#570 remove anchor opacity in disabled state, allow button to handle it
  framework/components/AButton/AButton.scss
Labels: 1.0.0-beta.59

#569 Add prop passing for tooltips on inline edits
  framework/components/AInlineInputBase/AInlineInputBase.js
  framework/components/AInlineInputBase/AInlineInputBase.mdx
  framework/components/AInlineInputBase/AInlineInputBase.scss
  framework/components/ATooltip/ATooltip.js
  framework/components/ATooltip/ATooltip.mdx
  framework/components/ATooltip/ATooltip.scss
Labels: 1.0.0-beta.59

#575 #573 - handleClick for item templates
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/AMultiSelect/AMultiSelect.mdx
Labels: 1.0.0-beta.60

#576 Fix tooltip for multiselect counter
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/AMultiSelect/AMultiSelectCounter.js
Labels: 1.0.0-beta.61
