Repository cisco-sbg-ui/magna-react, pull requests merged in 2023-05, with the labels that each got.

#319 feat: conditionally render modal and drawer children
  framework/components/ADrawer/ADrawer.cy.js
  framework/components/ADrawer/ADrawer.js
  framework/components/ADrawer/ADrawer.mdx
  framework/components/ADrawer/ADrawer.scss
  framework/components/AModal/AModal.cy.js
  framework/components/AModal/AModal.js
  framework/components/AModal/AModal.mdx
  framework/components/AModal/AModal.scss
  framework/utils/hooks.js
Labels: enhancement, breaking change

#383 docs(AModal): document delayUnmount prop
  framework/components/AModal/AModal.js
Labels: documentation

#408 fix: disable pointer events
  framework/components/AButton/AButton.scss
Labels: bug

#413 fix: hide icon when loading
  framework/components/AButton/AButton.cy.js
  framework/components/AButton/AButton.js
  framework/components/AButton/AButton.scss
Labels: enhancement
