Repository cisco-sbg-ui/magna-react, pull requests merged in 2024-03, with the labels that each got.

#639 Allow onKeyDown to activate edit mode on inline inputs
  framework/components/AInlineInputBase/AInlineInputBase.js
  framework/components/AInlineInputBase/AInlineInputBase.scss
Labels: 1.1.0-beta.14

#638 ASelect - differentiate placeholder from selected text
  framework/components/ASelect/ASelect.js
  framework/components/ASelect/ASelect.scss
Labels: 1.1.0-beta.14

#637 remove important from secondary text color
  framework/components/AButton/AButton.scss
Labels: 1.1.0-beta.14

#634 Allow node as child for AKeyValue
  framework/components/AKeyValue/AKeyValue.js
  framework/components/AKeyValue/AKeyValueTable.js
Labels: 1.1.0-beta.14

#640 Fix required label * color
  framework/components/AFieldBase/AFieldBase.js
  framework/components/AFieldBase/AFieldBase.scss
Labels: 1.1.0-beta.14

#635 fix-627 Add accessibility features to modals and drawers
  framework/components/ADrawer/ADrawer.js
  framework/components/ADrawer/ADrawer.mdx
  framework/components/ADrawer/ADrawer.scss
  framework/components/ADrawer/ADrawerTitle.js
  framework/components/AModal/AModal.cy.js
  framework/components/AModal/AModal.js
  framework/components/AModal/AModal.mdx
  framework/hooks/useOutsideClick/useOutsideClick.js
  framework/hooks/usePopupQuickExit/usePopupQuickExit.js
  framework/hooks/useReturnFocusOnClose/useReturnFocusOnClose.js
Labels: 1.1.0-beta.14, accessibility

#641 Phase 3 - Remove all references to palette
  framework/components/AApp/base/typography.scss
  framework/components/ABadge/ABadge.scss
  framework/components/ACarousel/_carousel.scss
  framework/components/AContextualNotification/AContextualNotification.scss
  framework/components/ADialog/ADialog.scss
  framework/components/AEmptyState/AEmptyState.scss
  framework/components/AHint/AHint.scss
  framework/components/AIcon/AIcon.scss
  framework/components/AInputBase/AInputBase.scss
  framework/components/ALoader/ACiscoLoader.scss
  framework/components/APanel/APanel.scss
  framework/components/ARadio/ARadio.scss
  framework/components/ASidebar/ASidebar.scss
  framework/components/ASlider/ASlider.scss
  framework/components/AStepper/AStepper.scss
  framework/components/ATabs/ATabs.scss
  framework/components/ATag/ATag.scss
  framework/components/ATooltip/ATooltip.scss
  framework/styles/utilities/variables.scss
Labels: enhancement, 1.1.0-beta.15

#644 Show tooltip on focusin; close on escape
  framework/components/ATriggerTooltip/ATriggerTooltip.js
Labels: accessibility

#642 Keyboard accessibility for ASwitch
  framework/components/ASwitch/ASwitch.cy.js
  framework/components/ASwitch/ASwitch.js
  framework/components/ASwitch/ASwitch.mdx
  framework/components/ASwitch/ASwitch.scss
Labels: accessibility, 1.1.0-beta.15

#645 Disabled pagination/#612
  framework/components/APagination/APagination.cy.js
  framework/components/APagination/APagination.js
  framework/components/APagination/APagination.scss
Labels: enhancement, 1.1.0-beta.15

#648 chore: updating PropTypes to clean up console warning
  framework/components/AEmptyState/AEmptyState.js
  framework/components/AModal/AModal.js
Labels: 1.1.0-beta.15

#649 Fix typo in css for disabled checked state
  framework/components/ARadio/ARadio.scss
Labels: 1.1.0-beta.15

#651 dep: bump cypress to 13.7.1
  package-lock.json
  package.json
Labels: dependencies

#661 MultiSelect readOnlyInput, fixes
  framework/components/AInputBase/AInputBase.scss
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/AMultiSelect/AMultiSelect.mdx
  framework/components/AMultiSelect/AMultiSelect.scss
Labels: 1.1.0-beta.15

#647 Add a null check for icon name
  framework/components/AIcon/AIcon.js
Labels: 1.1.0-beta.16

#653 Switch refs for modal accessibility tracking
  framework/components/ADrawer/ADrawer.js
  framework/components/ADrawer/ADrawer.scss
Labels: accessibility, 1.1.0-beta.16

#663 Fix tags for ACardBasic in examples
  framework/components/AModal/AModal.mdx
Labels: documentation

#657 Fix double focus for checkboxes with no label
  framework/components/ACheckbox/ACheckbox.js
Labels: accessibility, 1.1.0-beta.16

#666 feat: col width small option
  framework/components/ADataTable/ADataTable.mdx
  framework/components/ADataTable/ADataTable.scss
  framework/components/ADataTable/ADataTableCellTemplate.js
  framework/components/ADataTable/ADataTableHeader.js
  framework/components/ADataTable/ADataTableHeaderTemplate.js
  framework/components/ADataTable/ADataTableRowTemplate.js
Labels: 1.1.0-beta.16

#669 Revert modal changes, temporarily until 2.0.0
  framework/components/ADrawer/ADrawer.js
  framework/components/ADrawer/ADrawer.mdx
  framework/components/ADrawer/ADrawer.scss
  framework/components/ADrawer/ADrawerTitle.js
  framework/components/AModal/AModal.cy.js
  framework/components/AModal/AModal.js
  framework/components/AModal/AModal.mdx
  framework/hooks/useOutsideClick/useOutsideClick.js
  framework/hooks/usePopupQuickExit/usePopupQuickExit.js
  framework/hooks/useReturnFocusOnClose/useReturnFocusOnClose.js
Labels: 1.1.0-beta.17
