Repository cisco-sbg-ui/magna-react, pull requests merged in 2024-02, with the labels that each got.

#610 Add displayValue prop to inline inputs
  framework/components/AInlineInputBase/AInlineInputBase.js
Labels: 1.1.0-beta.10

#613 Add AKeyValue components
  framework/components/AKeyValue/AKeyValue.js
  framework/components/AKeyValue/AKeyValue.mdx
  framework/components/AKeyValue/AKeyValue.scss
  framework/components/AKeyValue/AKeyValueTable.js
  framework/components/AKeyValue/index.js
  framework/index.js
Labels: 1.1.0-beta.10

#614 feat: field base can have multiple hints
  framework/components/AAutocomplete/AAutocomplete.js
  framework/components/AButtonGroup/AButtonGroup.js
  framework/components/ACombobox/ACombobox.js
  framework/components/AFieldBase/AFieldBase.cy.js
  framework/components/AFieldBase/AFieldBase.js
  framework/components/AFieldBase/AFieldBase.mdx
  framework/components/AInputBase/AInputBase.js
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/ASelect/ASelect.js
  framework/components/ASlider/ASlider.js
  framework/components/ATextInput/ATextInput.js
  framework/components/ATextarea/ATextarea.js
Labels: 1.1.0-beta.10

#607 feat: start of var swap
  framework/components/AAccordion/AAccordion.scss
  framework/components/AAlert/AAlert.scss
  framework/components/AApp/AApp.scss
  framework/components/AApp/base/links.scss
  framework/components/AApp/base/typography.scss
  framework/components/AAutocomplete/AAutocomplete.scss
  framework/components/ABadge/ABadge.scss
  framework/components/ABreadcrumb/ABreadcrumb.scss
  framework/components/AButton/AButton.scss
  framework/components/AButtonGroup/AButtonGroup.scss
  framework/components/ACard/ACard.mdx
  framework/components/ACard/ACard.scss
  framework/components/ACheckbox/ACheckbox.scss
  framework/components/AContextualNotification/AContextualNotification.scss
  framework/components/AContextualNotificationMenu/AContextualNotificationMenu.scss
  framework/components/ADataTable/ADataTable.scss
  framework/components/ADatePicker/ADatePicker.scss
  framework/components/ADivider/ADivider.scss
  framework/components/ADrawer/ADrawer.scss
  framework/components/ADrawer/ADrawerFooter.scss
  framework/components/AEmptyState/AEmptyState.scss
  framework/components/AFieldBase/AFieldBase.scss
  framework/components/AFooter/AFooter.scss
  framework/components/AIcon/AIcon.scss
  framework/components/AInlineInputBase/AInlineInputBase.scss
  framework/components/AInputBase/AInputBase.scss
  framework/components/AList/AList.scss
  framework/components/AList/AListItemGroup.scss
  framework/components/ALoader/ADotLoader.scss
  framework/components/ALoader/ALoader.scss
  framework/components/ALoader/APageLoader.scss
  framework/components/AMenu/AMenu.scss
  framework/components/AMultiSelect/AMultiSelect.scss
  framework/components/APagination/APagination.scss
  framework/components/APanel/APanel.scss
  framework/components/APopover/APopover.scss
  framework/components/AProgressbar/AProgressbar.scss
  framework/components/ARadio/ARadio.scss
  framework/components/ASelect/ASelect.scss
  framework/components/ASimpleTable/ASimpleTable.scss
  framework/components/ASkeleton/ASkeleton.scss
  framework/components/ASlider/ASlider.scss
  framework/components/ASpinner/ASpinner.scss
  framework/components/AStepper/AStepper.scss
  framework/components/ASwitch/ASwitch.scss
  framework/components/ATabs/ATab.cy.js
  framework/components/ATabs/ATabs.scss
  framework/components/ATag/ATag.scss
  framework/components/ATextInput/ATextInput.scss
  framework/components/ATimeline/ATimeline.scss
  framework/components/AToast/AToast.scss
  framework/components/ATooltip/ATooltip.scss
  framework/components/ATree/ATree.scss
  framework/styles/theme/dark.scss
  framework/styles/theme/light.scss
  framework/styles/theme/theme-map.scss
  framework/styles/utilities/variables.scss
  package-lock.json
  package.json
Labels: enhancement, breaking change, 1.1.0-beta.11

#618 #616 - Add ARadioGroup, small variant, and description prop
  framework/components/ARadio/ARadio.js
  framework/components/ARadio/ARadio.mdx
  framework/components/ARadio/ARadio.scss
  framework/components/ARadio/ARadioGroup.js
  framework/components/ARadio/index.js
  framework/index.js
Labels: 1.1.0-beta.11

#619 fix: move new var theming out into ATheme
  framework/components/ATheme/ATheme.js
  framework/components/ATheme/ATheme.scss
  framework/styles/utilities/variables.scss
Labels: 1.1.0-beta.11

#622 Add more specificity to tag level anchor styling
  framework/components/AApp/base/links.scss
  framework/components/AButton/AButton.scss
Labels: 1.1.0-beta.12

#621 feature: accordion title has now way to place chevron icon to the left
  framework/components/AAccordion/AAccordion.mdx
  framework/components/AAccordion/AAccordion.scss
  framework/components/AAccordion/AAccordionHeaderTitle.js
Labels: 1.1.0-beta.12

#624 feat: add "gap" css helper class
  framework/components/AApp/base/helpers.scss
  package.json
Labels: enhancement

#625 feat: add `APageAlert` component
  framework/components/APageLayout/APageAlert.js
  framework/components/APageLayout/APageAlert.scss
  framework/components/APageLayout/APageLayout.mdx
  framework/components/APageLayout/index.js
  framework/index.js
Labels: enhancement

#626 Align icons for AInlineInput
  framework/components/AInlineInputBase/AInlineInputBase.scss
Labels: 1.1.0-beta.13

#623 Remove remaining theming references
  framework/components/AApp/AApp.scss
  framework/components/AAutocomplete/AAutocomplete.scss
  framework/components/ADataTable/ADataTable.scss
  framework/components/ADatePicker/ADatePicker.scss
  framework/components/ADrawer/ADrawerFooter.scss
  framework/components/AEmptyState/AEmptyState.scss
  framework/components/AIcon/AIcon.scss
  framework/components/AInlineInputBase/AInlineInputBase.scss
  framework/components/AInputBase/AInputBase.scss
  framework/components/AList/AList.scss
  framework/components/ALoader/APageLoader.scss
  framework/components/AMenu/AMenu.scss
  framework/components/APagination/APagination.scss
  framework/components/APanel/APanel.scss
  framework/components/APopover/APopover.scss
  framework/components/AProgressbar/AProgressbar.scss
  framework/components/ARadio/ARadio.scss
  framework/components/ASelect/ASelect.scss
  framework/components/ASimpleTable/ASimpleTable.scss
  framework/components/ASkeleton/ASkeleton.scss
  framework/components/ASlider/ASlider.scss
  framework/components/AStepper/AStepper.scss
  framework/components/ASwitch/ASwitch.scss
  framework/components/ATabs/ATabs.scss
  framework/components/ATag/ATag.scss
  framework/components/ATextInput/ATextInput.scss
  framework/components/ATheme/ATheme.scss
  framework/components/ATimeline/ATimeline.mdx
  framework/components/ATimeline/ATimeline.scss
  framework/components/AToast/AToast.scss
  framework/components/ATooltip/ATooltip.scss
  framework/components/ATree/ATree.scss
  framework/styles/index.scss
  framework/styles/magnetic-tokens/index.scss
  framework/styles/magnetic-tokens/theme-dark.scss
  framework/styles/magnetic-tokens/theme-light.scss
  framework/styles/theme/dark.scss
  framework/styles/theme/functions.scss
  framework/styles/theme/index.scss
  framework/styles/theme/light.scss
  framework/styles/theme/mixins.scss
  framework/styles/theme/theme-map.scss
  framework/styles/utilities/functions.scss
Labels: enhancement, 1.1.0-beta.13

#633 fix: lower z-index
  framework/components/ATimeline/ATimeline.scss
Labels: 1.1.0-beta.14
