Repository cisco-sbg-ui/magna-react, pull requests merged in 2024-08, with the labels that each got.

#821 fix: fix tooltip pointer position
  framework/components/AMenuBase/AMenuBase.tsx
Labels: bug, v2.3.2

#820 fix: pass isOpen boolean instead
  framework/components/ATriggerTooltip/ATriggerTooltip.tsx
Labels: v2.3.2

#818 Use useEscapeKeyDown for drawer
  framework/components/ADrawer/ADrawer.js
  framework/components/ADrawer/hooks.js
  framework/hooks/usePopupQuickExit/usePopupQuickExit.d.ts
  framework/hooks/usePopupQuickExit/usePopupQuickExit.ts
Labels: bug, v2.3.2

#822 chore: start of vetting types.
  framework/components/AActivityTimeline/types.ts
  framework/components/AAlert/types.ts
  framework/components/AApp/types.ts
  framework/components/AAutocomplete/types.ts
  framework/components/ABadge/types.ts
  framework/components/ABreadcrumb/types.ts
  framework/components/AButton/types.ts
  framework/components/AButtonGroup/types.ts
  framework/components/ACheckbox/types.ts
  framework/components/ACombobox/types.ts
  framework/components/AContextualNotification/types.ts
  framework/components/AContextualNotificationMenu/types.ts
  framework/components/ACopyButton/types.ts
  framework/components/ADataTable/types.ts
  framework/components/ADatePicker/types.ts
  framework/components/ADivider/types.ts
  framework/components/ADrawer/types.ts
  framework/components/AFieldBase/types.ts
  framework/components/AHint/types.ts
  framework/components/AInlineInputBase/types.ts
  framework/components/AInputBase/types.ts
  framework/components/AKeyValue/types.ts
  framework/components/ALayout/types.ts
  framework/components/AList/types.ts
  framework/components/ALoader/types.ts
  framework/components/AMenu/AMenu.d.ts
  framework/components/AMenu/types.ts
  framework/components/AMenuBase/types.ts
  framework/components/AModal/types.ts
  framework/components/AMount/types.ts
  framework/components/AMultiSelect/types.ts
  framework/components/APageLayout/types.ts
  framework/components/APagination/types.ts
  framework/components/APaginator/types.ts
  framework/components/APopover/types.ts
  framework/components/AProgressbar/types.ts
  framework/components/ARadio/types.ts
  framework/components/ASelect/types.ts
  framework/components/ASimpleTable/types.ts
  framework/components/ASkeleton/types.ts
  framework/components/ASlider/types.ts
  framework/components/ASpinner/types.ts
  framework/components/AStepper/types.ts
  framework/components/ASwitch/types.ts
  framework/components/ATag/types.ts
  framework/components/ATextInput/types.ts
  framework/components/ATextarea/types.ts
  framework/components/ATheme/ATheme.d.ts
  framework/components/ATheme/index.ts
  framework/components/ATheme/types.ts
  framework/components/AToast/types.ts
  framework/components/ATooltip/types.ts
  framework/components/ATree/types.ts
  framework/components/ATriggerTooltip/types.ts
  framework/types/index.ts
Labels: enhancement, v2.3.3

#824 Add boolean defaults, more docs
  framework/components/AAccordion/AAccordionPanel.tsx
  framework/components/AAccordion/types.ts
  framework/components/AActivityTimeline/AActivityTimelineItem.js
  framework/components/AActivityTimeline/types.ts
  framework/components/AAlert/types.ts
  framework/components/AAutocomplete/AAutocomplete.js
  framework/components/AAutocomplete/types.ts
  framework/components/AButton/AButton.js
  framework/components/AButton/types.ts
  framework/components/ACard/ACardBasic.js
  framework/components/ACard/ACardContainer.js
  framework/components/ACard/ACardItem.js
  framework/components/ACard/types.ts
  framework/components/ACheckbox/ACheckbox.js
  framework/components/ACheckbox/types.ts
  framework/components/ACombobox/ACombobox.js
  framework/components/ACombobox/types.ts
  framework/components/ADataTable/types.ts
  framework/components/ADivider/types.ts
  framework/components/ADrawer/ADrawerHeader.js
  framework/components/ADrawer/types.ts
Labels: documentation, v2.3.3

#826 fix: dismissible v dismissable logic
  framework/components/AAlert/AAlert.tsx
Labels: v2.3.3

#827 fix: some stray typings
  framework/components/AActivityTimeline/types.ts
  framework/components/AAutocomplete/types.ts
  framework/components/ACheckbox/types.ts
  framework/components/ACombobox/types.ts
  framework/components/AContextualNotificationMenu/types.ts
  framework/components/ADataTable/types.ts
  framework/components/ADatePicker/types.ts
  framework/components/AEmptyState/types.ts
  framework/components/AFieldBase/types.ts
  framework/components/AInView/types.ts
  framework/components/AInputBase/types.ts
  framework/components/AMenu/types.ts
  framework/components/AMultiSelect/types.ts
  framework/components/ANetworkValue/types.ts
  framework/components/APopover/types.ts
  framework/components/ARadio/types.ts
  framework/components/ASelect/types.ts
  framework/components/ASlider/types.ts
  framework/components/AStepper/types.ts
  framework/components/ASwitch/types.ts
  framework/components/ATextInput/types.ts
  framework/components/ATextarea/types.ts
  framework/components/AToaster/types.ts
  framework/components/ATree/types.ts
  framework/hooks/useEscapeKeydown/useEscapeKeydown.d.ts
  framework/hooks/usePopupQuickExit/usePopupQuickExit.ts
Labels: v.2.3.4

#828 fix: anetwork-value optional types
  framework/components/ANetworkValue/types.ts
Labels: v2.3.5

#831 Remove logic around scrollLeft/scrollTop for menu placement
  framework/components/AMenuBase/AMenuBase.tsx
Labels: v2.3.5

#830 Feat: Allow custom placeholder components
  framework/components/ASelect/ASelect.js
  framework/components/ASelect/ASelect.mdx
  framework/components/ASelect/types.ts
Labels: enhancement, v2.3.6

#837 dep: bump cypress to 13.13.2
  package-lock.json
  package.json
Labels: dependencies

#840 Unset stroke on some icons
  framework/components/AIcon/AIcon.scss
Labels: v2.3.9

#842 chore: missing type in a-card
  framework/components/ACard/types.ts
Labels: v2.3.9

#839 Progressbar updates/#789
  framework/components/AIcon/AIcon.scss
  framework/components/AIcon/AIcon.tsx
  framework/components/AIcon/magnaIcons.js
  framework/components/ALoader/ALoader.mdx
  framework/components/AProgressbar/AProgressbar.d.ts
  framework/components/AProgressbar/AProgressbar.js
  framework/components/AProgressbar/AProgressbar.mdx
  framework/components/AProgressbar/AProgressbar.scss
  framework/components/AProgressbar/AProgressbar.tsx
  framework/components/AProgressbar/constants.ts
  framework/components/AProgressbar/types.ts
  svg/status/alert.svg
Labels: enhancement, breaking change, v2.3.9

#844 feat: alert tag
  framework/components/ATag/ATag.js
  framework/components/ATag/ATag.mdx
  framework/components/ATag/ATag.scss
  framework/components/ATag/types.ts
Labels: enhancement, v2.3.9

#845 fix: Stray progressbar fixes
  framework/components/AProgressbar/AProgressbar.mdx
  framework/components/AProgressbar/AProgressbar.scss
  framework/components/AProgressbar/AProgressbar.tsx
  framework/components/AProgressbar/types.ts
Labels: bug

#846 fix: css label fix
  framework/components/AProgressbar/AProgressbar.scss
Labels: v2.4.1

#847 Unset stroke
  framework/components/AButton/AButton.scss
  framework/components/AIcon/AIcon.scss
  framework/components/ATag/ATag.scss
Labels: v2.4.1

#849 fix: breakpoints px
  framework/styles/utilities/variables.scss
Labels: bug, v2.4.1

#850 style: add padding
  pages/[[...route]]/index.scss
Labels: enhancement, v2.4.1

#851 A tag test
  framework/components/ATag/ATag.d.ts
  framework/components/ATag/ATag.spec.js
  framework/components/ATag/ATag.tsx
  framework/components/ATag/index.ts
  framework/components/ATag/types.ts
Labels: v2.4.1

#858 build: add react reference to avoid warnings
  tsconfig.json
Labels: dependencies, v2.4.1

#855 fix: add info and adjust mdx to latest figma
  framework/components/AEmptyState/AEmptyState.js
  framework/components/AEmptyState/AEmptyState.mdx
  framework/components/AEmptyState/AEmptyState.scss
  framework/components/AEmptyState/types.ts
Labels: v2.4.1

#854 Tag focus/hover fixes; hideStatusIcon prop
  framework/components/ATag/ATag.js
  framework/components/ATag/ATag.mdx
  framework/components/ATag/ATag.scss
  framework/components/ATag/ATag.tsx
  framework/components/ATag/types.ts
Labels: v2.4.1
