Repository cisco-sbg-ui/magna-react, pull requests merged in 2024-09, with the labels that each got.

#861 Adjust sizing for AAlert to match design
  framework/components/AAlert/AAlert.scss
Labels: v2.4.2

#863 build: eslint update
  .eslintrc.json
  package-lock.json
  package.json
Labels: dependencies

#862 build: add lib check for extra safety
  .eslintrc.json
  build/generate-babel-preset.js
  framework/components/ADrawer/ADrawerContent.d.ts
  framework/components/AInView/AInView.d.ts
  framework/components/AInlineInputBase/AInlineInputBase.d.ts
  framework/components/AInlineInputBase/index.ts
  framework/components/AInlineTextInput/AInlineTextInput.js
  framework/components/AInlineTextarea/AInlineTextarea.js
  framework/components/AList/AListItem.d.ts
  framework/components/ALoader/ALoader.d.ts
  framework/components/ALoader/types.ts
  framework/components/ATabs/ATabGroup.d.ts
  framework/components/ATheme/ATheme.d.ts
  framework/hooks/useABreakpoint/index.ts
  framework/hooks/useABreakpoint/types.ts
  framework/hooks/useABreakpoint/useABreakpoint.ts
  framework/hooks/useEscapeKeydown/useEscapeKeydown.d.ts
  framework/hooks/useKeydown/useKeydown.d.ts
  framework/types/index.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: v2.4.2

#864 fix: add some types in
  framework/components/ATag/ATag.tsx
Labels: v2.4.2

#865 Let next have its own tsconfig file
  next.config.js
  tsconfig.next.json
Labels: v2.4.3

#867 Add trial arrow icon
  framework/components/AIcon/iconMap.ts
  framework/components/AIcon/magnaIcons.js
  package.json
  svg/cursor.svg
Labels: v2.4.3

#866 deps: update cds 1.3.11
  package-lock.json
  package.json
Labels: dependencies, v2.4.3

#869 feat: add floating btn style, fix various styles and shadows across app
  framework/components/AButton/AButton.js
  framework/components/AButton/AButton.mdx
  framework/components/AButton/AButton.scss
  framework/components/AButton/types.ts
  framework/components/AContextualNotificationMenu/AContextualNotificationMenu.scss
  framework/components/APanel/APanel.scss
  framework/components/APopover/APopover.scss
  framework/components/ATheme/ATheme.scss
  framework/styles/utilities/mixins.scss
  framework/styles/utilities/variables.scss
Labels: enhancement, v2.4.3

#871 style: actually hide tab
  framework/components/ATabs/OverflowMenuTab.js
Labels: bug, v2.4.3

#873 style: fixs on panel header
  framework/components/APanel/APanel.scss
  framework/components/APopover/APopover.scss
  package-lock.json
Labels: v2.4.3

#872 Stop checking tab overflow once overflow is hit
  framework/components/ATabs/ATabGroup.js
Labels: v2.4.4

#859 Floating UI POC - Dropdown menus
  framework/components/AAutocomplete/AAutocomplete.js
  framework/components/AAutocomplete/AAutocomplete.spec.js
  framework/components/AAutocomplete/algolia.gi.fixture.json
  framework/components/ACombobox/ACombobox.js
  framework/components/AFloatingMenu/AFloatingMenu.d.ts
  framework/components/AFloatingMenu/AFloatingMenu.scss
  framework/components/AFloatingMenu/AFloatingMenu.tsx
  framework/components/AFloatingMenu/AFloatingMenuContainer.tsx
  framework/components/AFloatingMenu/index.ts
  framework/components/AFloatingMenu/types.ts
  framework/components/AFloatingMenu/useFloatingDropdown.tsx
  framework/components/AList/types.ts
  framework/components/AModal/AModal.mdx
  framework/components/AMount/AMount.js
  framework/components/AMultiSelect/AMultiSelect.cy.js
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/AMultiSelect/AMultiSelect.spec.js
  framework/components/ASelect/ASelect.cy.js
  framework/components/ASelect/ASelect.js
  package-lock.json
  package.json
Labels: dependencies, v2.4.4

#874 fix: fixes new random css ordering issue in amultiselect
  framework/components/AInputBase/AInputBase.scss
Labels: bug, v2.4.4

#876 fix: trying floating fix
  framework/components/AFloatingMenu/useFloatingDropdown.tsx
Labels: bug

#877 fix: variable icon
  framework/components/AButton/types.ts
  framework/components/AIcon/AIcon.scss
Labels: bug, v2.4.6

#878 fix: allow empty display
  framework/components/AFloatingMenu/useFloatingDropdown.tsx
  framework/components/AMultiSelect/AMultiSelect.js
Labels: bug, v2.4.6

#879 Use fixed strategy for dropdown menus
  framework/components/AFloatingMenu/AFloatingMenu.tsx
  framework/components/AFloatingMenu/useFloatingDropdown.tsx
Labels: bug, v2.4.6

#887 Fix flakey APaginator test
  framework/components/APaginator/APaginator.cy.js
Labels: v2.5.1

#888 deps: next bump
  next-env.d.ts
  package-lock.json
  package.json
Labels: dependencies, v2.5.1

#889 Attempt at fixing flakey tab test
  framework/components/ATabs/ATab.cy.js
Labels: v2.5.1

#884 Fix extra wide menus in Drawers/Modals, handle closeOnOutsideClick
  framework/components/AFloatingMenu/AFloatingMenu.tsx
  framework/components/AFloatingMenu/AFloatingMenuContainer.tsx
  framework/components/AFloatingMenu/useFloatingDropdown.tsx
Labels: bug, v2.5.1

#891 deps: upgrade cypress again
  .github/workflows/ci.yml
  framework/components/ATabs/ATab.cy.js
  package-lock.json
  package.json
Labels: dependencies

#897 Allow React.Node for non-array hints
  framework/components/AHint/AHintContainer.js
Labels: v2.5.3

#900 Disable reference hidden check for dropdown menus
  framework/components/AAutocomplete/AAutocomplete.js
  framework/components/ACombobox/ACombobox.js
  framework/components/AFloatingMenu/useFloatingDropdown.tsx
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/ASelect/ASelect.js
Labels: v2.5.3
