Repository cisco-sbg-ui/magna-react, pull requests merged in 2024-07, with the labels that each got.

#772 build: fix vulnerability and update packages with deprecations
  package-lock.json
  package.json
Labels: dependencies, v2.0.4

#764 Add magnetic compliant pagination component
  framework/components/AIcon/iconMap.js
  framework/components/AIcon/magnaIcons.js
  framework/components/APagination/APagination.mdx
  framework/components/APaginator/APaginator.cy.js
  framework/components/APaginator/APaginator.js
  framework/components/APaginator/APaginator.mdx
  framework/components/APaginator/APaginator.scss
  framework/components/APaginator/APaginatorButton.js
  framework/components/APaginator/APaginatorControls.js
  framework/components/APaginator/APaginatorNumbers.js
  framework/components/APaginator/APaginatorPageDetail.js
  framework/components/APaginator/APaginatorResultsSelector.js
  framework/components/APaginator/constants.js
  framework/components/APaginator/index.js
  framework/index.js
  svg/caret-line-left.svg
  svg/caret-line-right.svg
Labels: new component, v2.0.4

#775 build: update cds to 1.3.6
  package-lock.json
  package.json
Labels: dependencies

#777 fix(`AButton`): do not ignore `component` prop when rendered with `href` prop
  framework/components/AButton/AButton.js
Labels: bug

#782 Move css rules to resolve deprecation warnings in ordering
  framework/components/AAccordion/AAccordion.scss
  framework/components/ACard/ACard.scss
  framework/components/ADrawer/ADrawer.scss
  framework/components/AInputBase/AInputBase.scss
  framework/components/APagination/APagination.scss
  framework/components/ASimpleTable/ASimpleTable.scss
  framework/components/ATag/ATag.scss
  package-lock.json
  package.json
Labels: dependencies

#786 Typescript doc props
  .babelrc
  docs/Props.js
  framework/components/ACard/ACardBasic.js
  package-lock.json
  package.json
  pages/[[...route]]/index.js
Labels: v2.2.0

#783 Remove margin right for spinner inside button
  framework/components/AButton/AButton.js
  framework/components/AButton/AButton.scss
Labels: v2.2.0

#785 refactor: initiate typescript integration with cypress
  cypress.config.js
  cypress/support/commands.ts
  cypress/support/component.tsx
  cypress/support/e2e.ts
  cypress/support/index.d.ts
  cypress/tests/AAccordion.cy.tsx
  cypress/tests/useFocusTrap.cy.tsx
  cypress/tsconfig.json
  framework/components/AAccordion/types.ts
  framework/hooks/useFocusTrap/useFocusTrap.ts
Labels: v2.2.0

#792 787 - Adjust css to auto scroll modals to avoid running off the screen
  framework/components/AModal/AModal.mdx
  framework/components/AModal/AModal.scss
Labels: v2.2.0

#791 Add auto menu flip logic on bounds checking
  framework/components/AMenuBase/AMenuBase.tsx
  framework/components/AMenuBase/hooks.js
  framework/components/AMenuBase/types.ts
  framework/components/ATooltip/ATooltip.tsx
  framework/components/ATooltip/types.ts
  framework/components/ATriggerTooltip/ATriggerTooltip.cy.js
  framework/components/ATriggerTooltip/ATriggerTooltip.mdx
Labels: v2.2.0

#799 797 - Add tooltip prop pass through for the counter tag
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/AMultiSelect/AMultiSelectCounter.js
Labels: v2.2.0

#795 794 - don't validate disabled fields in forms; validate required empty array for multiselects
  framework/components/ACheckbox/ACheckbox.js
  framework/components/ACombobox/ACombobox.js
  framework/components/AForm/AForm.js
  framework/components/AInputBase/AInputBase.js
  framework/components/AMultiSelect/AMultiSelect.cy.js
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/ASelect/ASelect.js
  framework/components/ASlider/ASlider.js
  framework/components/ASwitch/ASwitch.js
  framework/components/ATextInput/ATextInput.js
  framework/components/ATextarea/ATextarea.js
Labels: v2.2.0

#806 Fix font color token for AFooter
  framework/components/AFooter/AFooter.scss
Labels: v2.2.3

#798 refactor: typescript for AAlert, AStep, AToast, and update deprecated keyCodes
  framework/components/AAccordion/AAccordionHeaderTitle.tsx
  framework/components/AAlert/AAlert.tsx
  framework/components/AAlert/types.ts
  framework/components/AAutocomplete/AAutocomplete.js
  framework/components/ACombobox/ACombobox.js
  framework/components/AContextualNotificationMenu/AContextualNotificationMenu.js
  framework/components/ADataTable/ADataTableHeaderTemplate.js
  framework/components/AInputBase/AInputBase.cy.js
  framework/components/AInputBase/AInputBase.js
  framework/components/AList/AListItem.js
  framework/components/AMenu/AMenu.js
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/APagination/APagination.js
  framework/components/APopover/APopover.js
  framework/components/ASelect/ASelect.js
  framework/components/ASlider/ASlider.js
  framework/components/AStepper/AStep.tsx
  framework/components/AStepper/AStepDescription.tsx
  framework/components/AStepper/AStepTitle.tsx
  framework/components/AStepper/AStepper.scss
  framework/components/AStepper/AStepper.tsx
  framework/components/AStepper/index.ts
  framework/components/AStepper/types.ts
  framework/components/ATag/ATag.js
  framework/components/ATextInput/ATextInput.js
  framework/components/AToast/AToast.tsx
  framework/components/AToast/types.ts
  framework/utils/helpers.js
Labels: v2.2.3

#807 Sync hints prop types across componnets; fix medium warning for AInputBase
  framework/components/AAutocomplete/AAutocomplete.js
  framework/components/AButtonGroup/AButtonGroup.js
  framework/components/ACombobox/ACombobox.js
  framework/components/AInputBase/AInputBase.js
  framework/components/AMultiSelect/AMultiSelect.js
  framework/components/ASelect/ASelect.js
  framework/components/ASlider/ASlider.js
  framework/components/ATextarea/ATextarea.js
Labels: v2.2.3

#805 Reposition open menus on scroll of a container
  framework/components/AMenuBase/AMenuBase.tsx
  framework/components/AModal/AModal.mdx
  framework/utils/helpers.js
  framework/utils/hooks.js
Labels: v2.2.3

#809 Remove redundant usePopupQuickExit in drawer hook
  framework/components/ADrawer/hooks.js
Labels: v2.2.4

#811 fix: cisco logo again
  framework/components/AIcon/AIcon.scss
Labels: bug, v2.2.4

#810 fix: skip .js files from d.ts generation for ts libraries
  tsconfig.json
Labels: v2.2.4

#817 fix: add back in indexd
  tsconfig.json
Labels: bug
