Repository cisco-sbg-ui/magna-react, pull requests merged in 2024-01, with the labels that each got.

#583 Fix typo in the proptype for onRowMouseLeave
  framework/components/ADataTable/ADataTable.js
Labels: 1.1.0-beta.2

#584 fix: #579 - add max-height for multiselect menu
  framework/components/AMultiSelect/AMultiSelect.scss
Labels: 1.1.0-beta.2

#585 chore: update vulnerability
  package-lock.json
  package.json
Labels: dependencies, 1.1.0-beta.2

#590 fix: add identifier
  framework/components/AList/AList.scss
Labels: bug, 1.1.0-beta.2

#592 Add react import for ADataTableWrapper
  framework/components/ADataTable/ADataTableWrapper.js
Labels: 1.1.0-beta.3

#595 Add generic prepend and append content to ATextInput
  framework/components/AInputBase/AInputBase.js
  framework/components/AInputBase/AInputBase.scss
  framework/components/ATextInput/ATextInput.cy.js
  framework/components/ATextInput/ATextInput.js
  framework/components/ATextInput/ATextInput.mdx
  framework/components/ATextInput/ATextInput.scss
Labels: 1.1.0-beta.4

#598 feat: add cds theme
  framework/components/ATheme/ATheme.js
  framework/styles/magnetic-tokens/index.scss
Labels: enhancement, 1.1.0-beta.4

#603 fix: allow tooltip trigger on webclamp
  framework/components/ATriggerTooltip/ATriggerTooltip.js
Labels: bug, 1.1.0-beta.9

#605 fix: menu overflow
  framework/components/AAccordion/AAccordion.scss
Labels: 1.1.0-beta.9
