Repository cisco-sbg-ui/magna-react, pull requests merged in 2024-12, with the labels that each got.

#965 ADrawer specified responsive sizes
  framework/components/ADrawer/ADrawer.cy.js
  framework/components/ADrawer/ADrawer.js
  framework/components/ADrawer/ADrawer.mdx
  framework/components/ADrawer/ADrawer.scss
  framework/components/ADrawer/types.ts
  framework/components/ATriggerBase/ATriggerBase.tsx
Labels: breaking change, v2.6.9

#968 A slider b/#949 - Add tests and Typescript
  cypress/tests/ABadge.cy.tsx
  cypress/tests/ASlider.cy.tsx
  eslint.config.mjs
  framework/components/AFieldBase/types.ts
  framework/components/ASlider/ASlider.d.ts
  framework/components/ASlider/ASlider.tsx
  framework/components/ASlider/types.ts
  framework/types/index.ts
Labels: enhancement, v2.6.9

#972 Adds new Entity icons
  framework/components/AIcon/AIcon.scss
  framework/components/AIcon/magnaIcons.js
  svg/app-window.svg
  svg/barcode.svg
  svg/brackets-curly.svg
  svg/certificate.svg
  svg/circuitry.svg
  svg/code-block.svg
  svg/gear-six.svg
  svg/hash.svg
  svg/seal-question.svg
  svg/seal-warning.svg
  svg/seal.svg
  svg/tag-chevron.svg
  svg/terminal-window.svg
  svg/user-focus.svg
  svg/wall.svg
Labels: enhancement, v2.6.9

#973 Fix colors for paginator prev/next stepper buttons
  framework/components/APagination/APagination.mdx
  framework/components/APaginator/APaginator.scss
  framework/components/ATriggerBase/ATriggerBase.tsx
Labels: v2.6.9

#975 docs: PR and versioning process
  README.md
Labels: documentation

#970 style remove global disabled style
  framework/components/AApp/base/reset.scss
  framework/components/AList/AList.scss
Labels: v2.6.9

#977 Fix: removed unused anchorRef in useFloatingBase
  framework/components/AFloatingBase/AFloatingBase.tsx
  framework/components/AFloatingBase/useFloatingBase.tsx
Labels: bug, v2.6.9

#961 Allow ADropdown to be controlled externally
  framework/components/ADropdown/ADropdown.cy.js
  framework/components/ADropdown/ADropdown.mdx
  framework/components/ADropdown/ADropdown.tsx
  framework/components/ADropdown/types.ts
  framework/components/AFloatingMenu/AFloatingMenu.tsx
  framework/components/AFloatingMenu/AFloatingMenuContainer.tsx
Labels: v2.7.0

#980 Feat/#978 timeline-updates
  .github/PULL_REQUEST_TEMPLATE.md
  framework/components/AActivityTimeline/AActivityTimeline.cy.js
  framework/components/AActivityTimeline/AActivityTimeline.js
  framework/components/AActivityTimeline/AActivityTimeline.mdx
  framework/components/AActivityTimeline/AActivityTimeline.scss
  framework/components/AActivityTimeline/AActivityTimelineItem.js
  framework/components/AActivityTimeline/types.ts
Labels: enhancement, v2.7.0

#981 Feat: turn on noUncheckedIndexedAccess
  framework/components/ASlider/ASlider.tsx
  framework/components/ATriggerBase/ATriggerBase.tsx
  framework/hooks/useOutsideClick/useOutsideClick.d.ts
  tsconfig.json
Labels: enhancement, v2.7.0
