Repository cisco-sbg-ui/magna-react, pull requests merged in 2024-06, with the labels that each got.

#740 Add release workflow
  .github/workflows/release.yml
Labels: v2.0.0

#739 proxy click router component as tab; don't style links at a global level for tabs
  framework/components/AApp/base/links.scss
  framework/components/ATabs/ATab.js
  framework/components/ATabs/ATabGroup.js
  framework/components/ATabs/ATabs.scss
  framework/utils/helpers.js
Labels: accessibility, v2.0.0

#752 chore: fix code highlighting
  framework/changelog.mdx
Labels: documentation

#756 Focus style update + fix on negative btn
  framework/components/AButton/AButton.scss
  framework/components/ADatePicker/ADatePicker.scss
  framework/components/AInputBase/AInputBase.scss
  framework/components/AMultiSelect/AMultiSelect.scss
  framework/styles/utilities/mixins.scss
Labels: enhancement, v2.0.2

#757 Fix usage of line height variables
  framework/components/AApp/base/typography.scss
  framework/components/AButton/AButton.scss
  framework/components/AToast/AToast.scss
  framework/components/ATooltip/ATooltip.scss
  framework/styles/utilities/variables.scss
Labels: v2.0.2

#760 Abstract hints logic into container for reuse
  framework/components/ACheckbox/ACheckbox.js
  framework/components/AFieldBase/AFieldBase.js
  framework/components/AHint/AHintContainer.js
  framework/components/ASwitch/ASwitch.js
Labels: v2.0.2

#767 Remove stroke from cisco icon
  framework/components/AIcon/AIcon.scss
Labels: v2.0.4

#766 Use .call in debounce function
  framework/utils/helpers.js
Labels: v2.0.4

#769 style: add extra pad to account for focus style
  framework/components/AButton/AButton.cy.js
  framework/styles/utilities/mixins.scss
Labels: v2.0.4
