Repository cisco-sbg-ui/magna-react, pull requests merged in 2024-11, with the labels that each got.

#951 Abstract ATooltipTrigger to a base component; Add ATriggerPopover
  framework/components/ACard/ACard.scss
  framework/components/AFloatingMenu/useFloatingDropdown.tsx
  framework/components/APopover/APopover.scss
  framework/components/ATriggerBase/ATriggerBase.tsx
  framework/components/ATriggerBase/index.ts
  framework/components/ATriggerBase/types.ts
  framework/components/ATriggerPopover/ATriggerPopover.cy.js
  framework/components/ATriggerPopover/ATriggerPopover.mdx
  framework/components/ATriggerPopover/ATriggerPopover.tsx
  framework/components/ATriggerPopover/index.ts
  framework/components/ATriggerPopover/types.ts
  framework/components/ATriggerTooltip/ATriggerTooltip.mdx
  framework/components/ATriggerTooltip/ATriggerTooltip.tsx
  framework/components/ATriggerTooltip/index.ts
  framework/components/ATriggerTooltip/types.ts
  framework/index.ts
Labels: v2.6.8

#947 Add a few OS icons
  framework/components/AIcon/AIcon.scss
  framework/components/AIcon/iconMap.ts
  framework/components/AIcon/magnaIcons.js
  svg/android-logo.svg
  svg/computer-tower.svg
  svg/device-mobile.svg
  svg/os/android-logo.svg
  svg/os/centos.svg
  svg/os/redhat.svg
  svg/os/ubuntu.svg
Labels: v2.6.8

#948 feat: dropdown icon
  framework/components/ADropdown/ADropdown.d.ts
  framework/components/ADropdown/ADropdown.mdx
  framework/components/ADropdown/ADropdown.tsx
  framework/components/ADropdown/types.ts
  framework/components/AFloatingMenu/useFloatingDropdown.tsx
Labels: enhancement, v2.6.8

#956 Add onShow/onHide callbacks for ATriggerTooltip
  framework/components/ATriggerBase/ATriggerBase.tsx
  framework/components/ATriggerBase/types.ts
  framework/components/ATriggerTooltip/ATriggerTooltip.mdx
  framework/hooks/useToggle/useToggle.d.ts
  framework/hooks/useToggle/useToggle.js
Labels: v2.6.8

#955 fix: add back string sizing in AIcon
  framework/components/AIcon/AIcon.mdx
  framework/components/AIcon/AIcon.scss
  framework/components/AIcon/AIcon.tsx
  framework/components/AIcon/types.ts
Labels: v2.6.8

#960 docs: update testing instuctions
  README.md
Labels: documentation

#959 style: remove hover color on tables
  framework/components/ASimpleTable/ASimpleTable.scss
Labels: v2.6.9

#964 Prevent inline edit icon from shrinking when at the edge of a container
  framework/components/AInlineInputBase/AInlineInputBase.scss
Labels: v2.6.9

#966 add new icons
  framework/components/AIcon/magnaIcons.js
  svg/device-mobile-speaker.svg
  svg/git-fork.svg
  svg/os/web-security-appliance.svg
Labels: v2.6.9
