Repository cisco-sbg-ui/magna-react, pull requests merged in 2024-10, with the labels that each got.

#903 Input disabled state should take precendence over readOnly
  framework/components/AInputBase/AInputBase.scss
Labels: v2.5.4

#905 Sync classes for AEmptyState variants with magnetic
  framework/components/AEmptyState/AEmptyState.js
  framework/components/AEmptyState/AEmptyState.scss
  framework/components/AEmptyState/types.ts
Labels: v2.5.4

#907 Re-enable isReferenceHidden check
  framework/components/AFloatingMenu/useFloatingDropdown.tsx
Labels: v2.5.4

#909 Tab again again
  framework/components/ATabs/ATab.cy.js
  package-lock.json
  package.json
Labels: v2.5.4

#911 Add extra specificity for multiselect width unset
  framework/components/AMultiSelect/AMultiSelect.scss
Labels: v2.5.5

#912 style: style danger to warning
  framework/components/AToast/AToast.scss
  framework/components/AToast/AToast.tsx
Labels: v2.5.5

#892 Use floating-ui for tooltips
  framework/components/ACopyButton/ACopyButton.scss
  framework/components/AFieldBase/AFieldBase.cy.js
  framework/components/AFloatingBase/AFloatingBase.scss
  framework/components/AFloatingBase/AFloatingBase.tsx
  framework/components/AFloatingBase/types.ts
  framework/components/AFloatingBase/useFloatingBase.tsx
  framework/components/AFloatingBase/utils.ts
  framework/components/AFloatingMenu/AFloatingMenu.tsx
  framework/components/AFloatingMenu/AFloatingMenuContainer.tsx
  framework/components/AFloatingMenu/types.ts
  framework/components/AFloatingMenu/useFloatingDropdown.tsx
  framework/components/ATooltip/ATooltip.mdx
  framework/components/ATooltip/ATooltip.scss
  framework/components/ATooltip/ATooltip.tsx
  framework/components/ATooltip/constants.tsx
  framework/components/ATooltip/types.ts
  framework/components/ATriggerTooltip/ATriggerTooltip.tsx
  framework/components/ATriggerTooltip/index.ts
  framework/components/ATriggerTooltip/types.ts
  framework/hooks/useToggle/useToggle.js
  framework/types/index.ts
Labels: v2.5.5

#913 Allow anchorRef to handle DOMRect
  framework/components/AFloatingBase/AFloatingBase.tsx
  framework/components/AFloatingBase/types.ts
  framework/components/AFloatingBase/useFloatingBase.tsx
  framework/components/ATooltip/ATooltip.tsx
  framework/components/ATriggerTooltip/ATriggerTooltip.tsx
  framework/types/types.ts
Labels: v2.5.5

#916 build: eslint9
  .eslintrc.json
  eslint.config.mjs
  framework/components/ADataTable/ADataTableCell.js
  package-lock.json
  package.json
Labels: enhancement, v2.5.5

#917 Add AEmptyState horizontal layout; align magnetic small/medium/large sizes
  framework/components/AEmptyState/AEmptyState.js
  framework/components/AEmptyState/AEmptyState.mdx
  framework/components/AEmptyState/AEmptyState.scss
  framework/components/AEmptyState/types.ts
Labels: v2.5.5

#919 Add .wokeignore
  .wokeignore
Labels: v2.6.1

#924 fix: alert close btn focus update
  framework/components/AAlert/AAlert.scss
  framework/components/AAlert/AAlert.tsx
Labels: v2.6.4

#937 fix flex spacing properties
  framework/components/AInputBase/AInputBase.scss
Labels: v2.6.6

#942 Add a null check for the hint container
  framework/components/AHint/AHintContainer.js
Labels: v2.6.6

#943 deps: run npm audit fix
  package-lock.json
Labels: dependencies

#935 Vertical divider/#932
  framework/components/ADivider/ADivider.d.ts
  framework/components/ADivider/ADivider.mdx
  framework/components/ADivider/ADivider.scss
  framework/components/ADivider/ADivider.tsx
  framework/components/ADivider/types.ts
Labels: v2.6.7

#940 Icon update/#931
  framework/components/AIcon/AIcon.mdx
  framework/components/AIcon/AIcon.scss
  framework/components/AIcon/AIcon.tsx
  framework/components/AIcon/magnaIcons.js
  framework/components/AIcon/types.ts
  svg/application.svg
  svg/arrows-in-cardinal.svg
  svg/camera.svg
  svg/cellular-gateway.svg
  svg/crosshair.svg
  svg/envelope-simple.svg
  svg/generic-client.svg
  svg/generic-device.svg
  svg/globe-simple.svg
  svg/leaf.svg
  svg/magic-wand.svg
  svg/magnet.svg
  svg/map-trifold.svg
  svg/paperclip.svg
  svg/passthrough.svg
  svg/placeholder.svg
  svg/play-circle.svg
  svg/plug-small.svg
  svg/printer.svg
  svg/rocket.svg
  svg/sensor.svg
  svg/stack-port.svg
  svg/status/deny.svg
  svg/switch.svg
  svg/teleworker-gateway.svg
  svg/trash-simple.svg
  svg/unsyncd/Loader.svg
  svg/wan-application.svg
  svg/wifi-lightning.svg
  svg/wifi-low.svg
  svg/wifi-medium.svg
  svg/wifi-slash.svg
  svg/wifi-x.svg
  svg/wireless-lan-controller.svg
Labels: enhancement, v2.6.7

#946 Badges/#934
  cypress/tests/ABadge.cy.tsx
  cypress/tests/helpers.ts
  framework/components/ABadge/ABadge.d.ts
  framework/components/ABadge/ABadge.js
  framework/components/ABadge/ABadge.mdx
  framework/components/ABadge/ABadge.scss
  framework/components/ABadge/ABadge.tsx
  framework/components/ABadge/types.ts
Labels: enhancement, v2.6.7

#945 Allow ASkeleton components to be used without the wrapper
  framework/components/ASkeleton/ASkeleton.mdx
  framework/components/ASkeleton/ASkeleton.scss
  framework/components/ASkeleton/ASkeletonBlock.js
  framework/components/ASkeleton/ASkeletonText.js
  framework/components/ASkeleton/types.ts
Labels: v2.6.7

#952 docs: update PR language
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation
