Repository cisco-sbg-ui/magna-react, pull requests merged in 2024-05, with the labels that each got.

#688 chore: remove palette, color-helpers, and theme folder
  framework/changelog.mdx
  framework/components/AApp/AApp.scss
  framework/components/AApp/base/color-helpers.scss
  framework/components/AContextualNotification/AContextualNotification.scss
  framework/styles/theme/theme-map.scss
  framework/styles/utilities/index.scss
  framework/styles/utilities/palette.scss
Labels: breaking change

#697 feat: add activity timeline components
  framework/components/AActivityTimeline/AActivityTimeline.cy.js
  framework/components/AActivityTimeline/AActivityTimeline.js
  framework/components/AActivityTimeline/AActivityTimeline.mdx
  framework/components/AActivityTimeline/AActivityTimeline.scss
  framework/components/AActivityTimeline/AActivityTimelineItem.js
  framework/components/AActivityTimeline/AActivityTimelineItemTitle.js
  framework/components/AActivityTimeline/components/AActivityTimelineItemBody.js
  framework/components/AActivityTimeline/components/AActivityTimelineItemDivider.js
  framework/components/AActivityTimeline/components/AActivityTimelineItemHeader.js
  framework/components/AActivityTimeline/components/AActivityTimelineItemHeaderContent.js
  framework/components/AActivityTimeline/components/AActivityTimelineItemHeaderToggleButton.js
  framework/components/AActivityTimeline/components/AActivityTimelineListItem.js
  framework/components/AActivityTimeline/icons/CompleteIcon.js
  framework/components/AActivityTimeline/icons/ErrorIcon.js
  framework/components/AActivityTimeline/icons/IncompleteIcon.js
  framework/components/AActivityTimeline/icons/NeutralIcon.js
  framework/components/AActivityTimeline/icons/ProgressIcon.js
  framework/components/AActivityTimeline/icons/README.md
  framework/components/AActivityTimeline/index.js
  framework/index.js
Labels: enhancement

#706 Refactor tab selected tracking; add arrow key accessibility
  framework/changelog.mdx
  framework/components/ATabs/ATab.cy.js
  framework/components/ATabs/ATab.js
  framework/components/ATabs/ATabGroup.js
  framework/components/ATabs/ATabs.mdx
  framework/components/ATabs/ATabs.scss
  framework/components/ATabs/OverflowMenuTab.js
Labels: accessibility

#660 Add focus trap to AMenu
  framework/components/AList/AList.scss
  framework/components/AMenu/AMenu.cy.js
  framework/components/AMenu/AMenu.js
  framework/components/ASelect/ASelect.js
  framework/components/ATabs/ATab.cy.js
  framework/components/ATabs/ATabGroup.js
Labels: accessibility

#716 Update breakpoints to magnetic spec; move code into hooks
  framework/changelog.mdx
  framework/components/AApp/AApp.mdx
  framework/components/ABreakpoint/ABreakpoint.spec.js
  framework/components/ABreakpoint/index.js
  framework/hooks/useABreakpoint/index.js
  framework/hooks/useABreakpoint/useABreakpoint.js
  framework/hooks/useABreakpoint/useABreakpoint.mdx
  framework/index.js
  framework/styles/utilities/variables.scss
Labels: breaking change

#719 #718 - add react import to helpers
  framework/utils/helpers.js
Labels: BACKPORT

#722 fix: spread props in `AActivityTimelineItem` component
  framework/components/AActivityTimeline/AActivityTimelineItem.js
  framework/components/AActivityTimeline/components/AActivityTimelineListItem.js
Labels: bug

#727 Dropdown/#721
  framework/components/AButton/AButton.js
  framework/components/AButton/AButton.mdx
  framework/components/ADropdown/ADropdown.cy.js
  framework/components/ADropdown/ADropdown.js
  framework/components/ADropdown/ADropdown.mdx
  framework/components/ADropdown/index.js
  framework/components/AMenu/AMenu.mdx
  framework/index.js
  framework/styles/utilities/mixins.scss
Labels: enhancement

#731 build: deps security update
  package-lock.json
  package.json
Labels: dependencies, v2.0.0

#732 fix: code style
  framework/components/AApp/base/typography.scss
Labels: v2.0.0

#735 chore: #733 color adjustments, #730 console warn
  framework/components/AActivityTimeline/AActivityTimeline.mdx
  framework/components/AActivityTimeline/AActivityTimeline.scss
Labels: v2.0.0
