Repository cisco-sbg-ui/magna-react, pull requests merged in 2025-01, with the labels that each got.

#979 Feature: AUpload component
  .gitignore
  framework/components/ALoader/ALoader.mdx
  framework/components/AUpload/AUpload.cy.js
  framework/components/AUpload/AUpload.mdx
  framework/components/AUpload/AUpload.scss
  framework/components/AUpload/AUpload.tsx
  framework/components/AUpload/index.ts
  framework/components/AUpload/types.ts
  framework/index.ts
  framework/types/index.ts
  package-lock.json
  package.json
Labels: v2.7.1

#987 fix: reduce useEffect call back to 1
  framework/components/ATheme/ATheme.js
Labels: v2.7.1

#993 fix(APageAlert): refine prop types
  framework/components/APageLayout/APageAlert.d.ts
  framework/components/APageLayout/APageAlert.js
  framework/components/APageLayout/types.ts
Labels: v2.7.2

#992 Bugfix ADrawer Responsive width array based prop type
  framework/components/ADrawer/ADrawer.js
Labels: v2.7.2

#996 fix(AActivityTimeline): add space between header and body
  framework/components/AActivityTimeline/AActivityTimeline.scss
Labels: bug, v2.7.2

#994 deps: update next.js
  package-lock.json
  package.json
Labels: dependencies, v2.7.2

#995 chore: remove scss tokens from repo, update CDS
  framework/components/ATabs/ATabs.scss
  framework/components/ATheme/ATheme.scss
  framework/styles/magnetic-tokens/index.scss
  framework/styles/utilities/index.scss
  package-lock.json
  package.json
Labels: dependencies, v2.7.3

#991 Refactor/#978 timeline
  framework/components/AActivityTimeline/AActivityTimeline.d.ts
  framework/components/AActivityTimeline/AActivityTimeline.mdx
  framework/components/AActivityTimeline/AActivityTimeline.tsx
  framework/components/AActivityTimeline/AActivityTimelineItem.d.ts
  framework/components/AActivityTimeline/AActivityTimelineItem.tsx
  framework/components/AActivityTimeline/AActivityTimelineItemTitle.d.ts
  framework/components/AActivityTimeline/AActivityTimelineItemTitle.js
  framework/components/AActivityTimeline/AActivityTimelineItemTitle.tsx
  framework/components/AActivityTimeline/components/AActivityTimelineItemBody.tsx
  framework/components/AActivityTimeline/components/AActivityTimelineItemDivider.js
  framework/components/AActivityTimeline/components/AActivityTimelineItemDivider.tsx
  framework/components/AActivityTimeline/components/AActivityTimelineItemHeader.tsx
  framework/components/AActivityTimeline/components/AActivityTimelineItemHeaderContent.tsx
  framework/components/AActivityTimeline/components/AActivityTimelineItemHeaderToggleButton.tsx
  framework/components/AActivityTimeline/components/AActivityTimelineListItem.tsx
  framework/components/AActivityTimeline/types.ts
  framework/components/ATimeline/ATimeline.d.ts
  framework/components/ATimeline/ATimeline.js
  framework/components/ATimeline/ATimeline.mdx
  framework/components/ATimeline/ATimeline.scss
  framework/components/ATimeline/ATimeline.spec.js
  framework/components/ATimeline/ATimelineItem.d.ts
  framework/components/ATimeline/ATimelineItem.js
  framework/components/ATimeline/ATimelineItemBody.d.ts
  framework/components/ATimeline/ATimelineItemBody.js
  framework/components/ATimeline/ATimelineItemTitle.d.ts
  framework/components/ATimeline/ATimelineItemTitle.js
  framework/components/ATimeline/index.ts
  framework/components/ATimeline/types.ts
  framework/index.ts
  framework/types/index.ts
Labels: v2.7.3

#1001 Add tertiary destructive button state
  framework/components/AButton/AButton.js
  framework/components/AButton/AButton.mdx
  framework/components/AButton/AButton.scss
Labels: v2.7.3

#1002 feat(APageAlert): add "AToast" props to types
  framework/components/APageLayout/APageAlert.js
  framework/components/APageLayout/types.ts
Labels: v2.7.3

#998 Feature/Fix: Add icons and clean up older icons
  framework/components/AIcon/AIcon.scss
  framework/components/AIcon/AIcon.tsx
  framework/components/AIcon/magnaIcons.js
  svg/Tag.svg
  svg/chat-dots.svg
  svg/device-tablet-speaker.svg
  svg/hard-drive.svg
  svg/hard-drives.svg
  svg/image.svg
  svg/lock.svg
  svg/os/android-logo.svg
  svg/os/centos.svg
  svg/os/oracle.svg
  svg/os/web-security-appliance.svg
  svg/skull.svg
  svg/smiley-x-eyes.svg
  svg/status/Info.svg
  svg/status/alert.svg
  svg/status/allow.svg
  svg/status/deny.svg
  svg/status/disabled.svg
  svg/status/excellent.svg
  svg/status/in-progress.svg
  svg/status/inactive.svg
  svg/status/low-warning.svg
  svg/status/negative.svg
  svg/status/positive.svg
  svg/status/severe-warning.svg
  svg/status/warning.svg
  svg/text-bolder.svg
Labels: v2.7.3
